[package]
name = "brancharch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = []
debug-trace-execution = [ "debug" ]
noprint = []

[dependencies]
num_enum = "0.7.2"
rand = "0.8.5"
